### ISSUE TITLE
getControl crashes BIRT

### ISSUE THREAD

**Issue by wimjongman** [eclipse/gef-classic#154]
The latest GEF crashes BIRT because the PalletteViewPage got a new getControl method that does not do a null check. Apparently, there can be a dispose before the part has been properly created. 

<details>
java.lang.NullPointerException: Cannot invoke "org.eclipse.gef.ui.palette.PaletteViewer.getControl()" because "this.viewer" is null
	at org.eclipse.gef.ui.views.palette.PaletteViewerPage.getControl(PaletteViewerPage.java:96)
	at org.eclipse.ui.part.Page.dispose(Page.java:74)
	at org.eclipse.gef.ui.views.palette.PaletteViewerPage.dispose(PaletteViewerPage.java:72)
	at org.eclipse.birt.report.designer.internal.ui.editors.parts.GraphicalEditorWithFlyoutPalette$CustomPalettePage.dispose(GraphicalEditorWithFlyoutPalette.java:729)
	at org.eclipse.birt.report.designer.internal.ui.editors.schematic.ReportMultiBookPage.dispose(ReportMultiBookPage.java:84)
	at org.eclipse.birt.report.designer.ui.editors.MultiPageReportEditor.dispose(MultiPageReportEditor.java:1210)
	at org.eclipse.birt.report.designer.ui.editors.IDEMultiPageReportEditor.dispose(IDEMultiPageReportEditor.java:414)
	at org.eclipse.birt.report.designer.ui.editors.ReportEditorProxy.dispose(ReportEditorProxy.java:144)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.invalidate(CompatibilityPart.java:264)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.destroy(CompatibilityPart.java:421)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

</details>

**Comment by wimjongman** [comment]
I spoke too soon. The code is there already since 2010. Something inside Eclipse must have changed. This worked fine in 2022-12. However, it would not hurt to do a null check here. Can I make a PR for it? https://github.com/eclipse/gef-classic/blob/608691122b37d926a4b6f4ba23571a68a8db063e/org.eclipse.gef/src/org/eclipse/gef/ui/views/palette/PaletteViewerPage.java#L95-L97

**Comment by azoitl** [comment]
I was about to write that I was not aware that we changed anything there. Then I saw your second comment. I'm not sure why it never effected any other GEF Classic based editor but I you are right I null check want hurt here. Happy if you can provide a PR for it.

**Comment by wimjongman** [comment]
As you can see from the stack trace, it comes from below:
 `org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.destroy(CompatibilityPart.java:421) at... `

**Comment by Phillipus** [comment]
Would be interesting to breakpoint it and see if it was being called twice, though.

**Comment by azoitl** [comment]
and if it is null in all cases

**Comment by Destrolaric** [comment]
As I remember, interaction with e4 was added by me for theming. Probably now, it may cause null disposal if there is no check.

**Comment by wimjongman** [comment]
After debugging further, I found the real cause of the error. This NPE was just a symptom.

The problem is inside BIRT. We do not return a correct instance of an adapter class that now trips gef because of this recent change:

https://github.com/eclipse/gef-classic/blob/608691122b37d926a4b6f4ba23571a68a8db063e/org.eclipse.gef/src/org/eclipse/gef/ui/views/palette/PaletteView.java#L94-L100

In the past, we could safely pass whatever, but this is no longer allowed.

**Comment by wimjongman** [comment]
Thinking about this a bit more... Should Gef assume that all clients return an instance of the adapter? Surely it is wrong if they don't, but it will cause a ClassCastException that will now break the GUI in unpleasant ways. Maybe Gef could catch the CCE since the generic adapter type is quite new and the adapter framework was quite forgiving in the past when only Object was passed around.

**Comment by azoitl** [comment]
@wimjongman thx for this thorough analysis. Yes this is strange but important to know. I just came across another similar problem yesterday. Where I have implemented also a rather strict fix. Looking at the code The second cast to IPAgeBookViewPage seems to be rather dangerous. So even when we bring back the old code something should be done here. What would you suggest?

**Comment by wimjongman** [comment]
The PalettePage code is IPageBookViewPage according to its interface:

```
public interface PalettePage extends IPageBookViewPage {
}
```

**Comment by wimjongman** [comment]
> What would you suggest?

I suggest waiting for more reports before reverting. Strictly, GEF is right not to accept wrong types from getAdapter.

**Comment by wimjongman** [comment]
PalettePage and IPageBookViewPage are the same, so I suggest keeping everything else the same. BIRT is checking for `type == PalettePage.class`, so changing this will break us again.

https://github.com/eclipse/birt/blob/b3c67677d7f892e9a2d3e2917d152d1d347a42d4/UI/org.eclipse.birt.report.designer.ui.editors/src/org/eclipse/birt/report/designer/ui/editors/MultiPageReportEditor.java#L552

**Comment by azoitl** [comment]
I also wanted to point out that clients most probably are checking for the `PalettePage.class` and we shouldn't change that.

**Comment by azoitl** [comment]
In the mean time I checked with Eclipse GMF Runtime and Eclipse Graphiti. They both behave correctly. To be honest only GMF Runtime has an own page but correctly inherits from GEF Classic classes.

I'm sorry @wimjongman that this effected BIRT. But in the end as you wrote it will make Eclipse GEF and BIRT better.

As I heads up I have another potentially problematic commit coming up: https://github.com/azoitl/gef-classic/commit/69194fbf80e0c9b545788f662807c775d26ad6af
Similar to this change the documentation and implementation didn't match.
