### ISSUE TITLE
Possible regression caused by [#155] Typed node list

### ISSUE THREAD

**Issue by pcdavid** [eclipse/gef-classic#245]
I'm working on updating GMF Runtime to the recent API changes (generic types).
Using the very latest GEF nightly, I have a version of GMF that compiles again, *but* one of the unit tests is broken with that version. From [this job](https://ci.eclipse.org/gmf-runtime/job/gmf-runtime-all/PLATFORM=canary,jdk=openjdk-jdk17-latest,label=migration/101/console):

```
18:02:53 org.eclipse.gmf.tests.runtime.draw2d.ui.graph.CompositeGraphLayoutTest.testVirtualNodeCreation -- Time elapsed: 0.010 s <<< ERROR!
18:02:53 java.lang.RuntimeException: Cycle detected in graph
18:02:53 	at org.eclipse.draw2d.graph.InitialRankSolver.solve(InitialRankSolver.java:58)
18:02:53 	at org.eclipse.draw2d.graph.InitialRankSolver.visit(InitialRankSolver.java:37)
18:02:53 	at org.eclipse.draw2d.graph.DirectedGraphLayout.visit(DirectedGraphLayout.java:106)
18:02:53 	at org.eclipse.gmf.runtime.draw2d.ui.graph.GMFDirectedGraphLayout.visit(GMFDirectedGraphLayout.java:36)
18:02:53 	at org.eclipse.gmf.runtime.draw2d.ui.internal.graph.CompositeDirectedGraphLayout.layoutNodes(CompositeDirectedGraphLayout.java:98)
18:02:53 	at org.eclipse.gmf.runtime.draw2d.ui.internal.graph.CompositeDirectedGraphLayout.layoutNodes(CompositeDirectedGraphLayout.java:78)
18:02:53 	at org.eclipse.gmf.runtime.draw2d.ui.internal.graph.CompositeDirectedGraphLayout.visit(CompositeDirectedGraphLayout.java:52)
18:02:53 	at org.eclipse.gmf.tests.runtime.draw2d.ui.graph.CompositeGraphLayoutTest.testVirtualNodeCreation(CompositeGraphLayoutTest.java:64)
18:02:53 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:02:53 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
18:02:53 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:02:53 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
18:02:53 	at junit.framework.TestCase.runTest(TestCase.java:177)
18:02:53 	at junit.framework.TestCase.runBare(TestCase.java:142)
18:02:53 	at junit.framework.TestResult$1.protect(TestResult.java:122)
18:02:53 	at junit.framework.TestResult.runProtected(TestResult.java:142)
```

Indeed, I confirmed locally using `git bisect` that [the test in question](https://github.com/eclipse/gmf-runtime/blob/master/bundles/org.eclipse.gmf.tests.runtime.draw2d.ui/src/org/eclipse/gmf/tests/runtime/draw2d/ui/graph/CompositeGraphLayoutTest.java#L39) fails since https://github.com/eclipse/gef-classic/pull/234.

**Comment by pcdavid** [comment]
To test:
1. Import the latest version of GMF Runtime (you'll need at least https://github.com/eclipse/gmf-runtime/commit/f5c4f5ae88d835d1213144ba8190131635094ddc to get something that compiles with GEF Class master) in a workspace git GEF Classic master.
2. Run `org.eclipse.gmf.tests.runtime.draw2d.ui.graph.CompositeGraphLayoutTest` as a JUnit Plug-in test.
3. On GEF Classic master (2312b49ce at the moment I'm writing), it fails with the above stack.
4. Switch to eb1d17a5c (just before the changes in #245), wait for the rebuild, and re-launch the GMF Runtime test: it passes.

**Comment by pcdavid** [comment]
It seems the behavior change is caused by the change in `BreakCylces.java` in https://github.com/eclipse/gef-classic/commit/31a70127f763d40fd1f6eb6a56de9158cf9538ce#diff-cb74059f329254e6b1320150a0474f3e927f5a7aab9298721aa9e57e8fc9462b

I've re-read it and don't see anything obvious. I'm reverting each individual change to pinpoint the bad one.

**Comment by pcdavid** [comment]
The change in `visit(DirectedGraph g)` at least seems wrong:

Before:
```java
public void visit(DirectedGraph g) {
	// put all nodes in list, initialize index
	graphNodes.resetFlags();
	for (int i = 0; i < g.nodes.size(); i++) {
		Node n = g.nodes.getNode(i);
		setIncomingCount(n, n.incoming.size());
		graphNodes.add(n);
	}
```

After:
```java
@Override
public void visit(DirectedGraph g) {
	// put all nodes in list, initialize index
	graphNodes.resetFlags();
	for (Node n : graphNodes) {
		setIncomingCount(n, n.incoming.size());
		graphNodes.add(n);
	}
```

The new version of the `for` loop iterates on `graphNodes` instead of `g.nodes`.

However, just reverting it changes the test failure into a ConcurrentModificationException:

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at org.eclipse.draw2d.graph.PopulateRanks.visit(PopulateRanks.java:47)
	at org.eclipse.draw2d.graph.DirectedGraphLayout.visit(DirectedGraphLayout.java:106)
	at org.eclipse.gmf.runtime.draw2d.ui.graph.GMFDirectedGraphLayout.visit(GMFDirectedGraphLayout.java:36)
	at org.eclipse.gmf.runtime.draw2d.ui.internal.graph.CompositeDirectedGraphLayout.layoutNodes(CompositeDirectedGraphLayout.java:98)
	at org.eclipse.gmf.runtime.draw2d.ui.internal.graph.CompositeDirectedGraphLayout.layoutNodes(CompositeDirectedGraphLayout.java:78)
	at org.eclipse.gmf.runtime.draw2d.ui.internal.graph.CompositeDirectedGraphLayout.visit(CompositeDirectedGraphLayout.java:52)
	at org.eclipse.gmf.tests.runtime.draw2d.ui.graph.CompositeGraphLayoutTest.testVirtualNodeCreation(CompositeGraphLayoutTest.java:64)
```

**Comment by pcdavid** [comment]
The GMF Runtime build & tests are green again using the most recent GEF build.
Thanks @ptziegler and @azoitl for the reactivity. :+1:
