### ISSUE TITLE
Improved handling of null values in AbstractEditPartViewer

### ISSUE THREAD

**Issue by ptziegler** [eclipse/gef-classic#433]
This is an error I just encountered while implementing a new graphical viewer:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.gef.EditPart.setSelected(int)" because "part" is null
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.lambda$3(AbstractEditPartViewer.java:499)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.primDeselectAll(AbstractEditPartViewer.java:499)
	at org.eclipse.gef.ui.parts.AbstractEditPartViewer.select(AbstractEditPartViewer.java:634)
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable.setActivePropertyInfo(PropertyTable.java:941)
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable.handleMouseDown(PropertyTable.java:340)
	at org.eclipse.wb.internal.core.model.property.table.PropertyTable$1.mouseDown(PropertyTable.java:174)
```

Cause seems to be that `null` is among the selected edit parts. Based on the exception, I assume that this is an unexpected state.
I think the `select()` method should either ignore those values or all methods working on the selection should have an additional null-check.

**Comment by azoitl** [comment]
You are right, I also don't think that there should be a null in the list of selected EditParts. A protection should be added. I looked a bit into the code and I think the `SelectionManager` would be the right place for that. 

However while writing this I had a second look. In all methods where you would update the selection with a null `EditPart` an NPE would allready be thrown there. So this means you must  have another location where you modify the selection list of the `AbstractViewer`.  I guess there is little on GEF side we could do. What would be good to have the `AbstractViewer`'s `selection` list private. But I guess that is a change we can not easily do.

**Comment by ptziegler** [comment]
> However while writing this I had a second look. In all methods where you would update the selection with a null EditPart an NPE would allready be thrown there. So this means you must have another location where you modify the selection list of the AbstractViewer.

I already know what the problem is. I called `EditPart editPart = findObjectAt(x, y)`, followed by `select(editPart)`, without checking whether `editPart` is null.

My point is that the error message is rather cryptic, and I think we should directly check whether the argument is null, when invoking `select(EditPart)`.
