### ISSUE TITLE
"IllegalStateException: Workbench has not been created yet." on loading PinFigure

### ISSUE THREAD

**Issue by cedric780** [eclipse/gef-classic#580]
Hello,
I am trying to migrate our product from old GEF (3.11 I think) to last gef-classic , and I have a "IllegalStateException: Workbench has not been created yet." error that prevent any GEF view to display.

Our product is a pure Eclipse 4 RCP application that nevers start the Eclipse 3 workbench.

```
java.lang.ExceptionInInitializerError: null
	at org.eclipse.gef.internal.ui.palette.editparts.PinFigure.<init>(PinFigure.java:45)
	at org.eclipse.gef.internal.ui.palette.editparts.DrawerFigure.<init>(DrawerFigure.java:169)
	at org.eclipse.gef.internal.ui.palette.editparts.DrawerEditPart$1.<init>(DrawerEditPart.java:68)
	at org.eclipse.gef.internal.ui.palette.editparts.DrawerEditPart.createFigure(DrawerEditPart.java:68)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.getFigure(AbstractGraphicalEditPart.java:473)
	at org.eclipse.gef.internal.ui.palette.editparts.DrawerEditPart.getFigure(DrawerEditPart.java:117)
	at org.eclipse.gef.internal.ui.palette.editparts.DrawerEditPart.getFigure(DrawerEditPart.java:1)
	at org.eclipse.gef.editparts.AbstractGraphicalEditPart.addChildVisual(AbstractGraphicalEditPart.java:210)
	at org.eclipse.gef.editparts.AbstractEditPart.addChild(AbstractEditPart.java:219)
        ... stripped out ...
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:681)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1262)
	at org.modelio.platform.rcp.inputpart.InputPartService.showInputPart(InputPartService.java:155)
	at org.modelio.diagram.editor.plugin.DiagramEditorsManager.lambda$0(DiagramEditorsManager.java:134)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4047)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3663)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1042)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:152)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:165)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Caused by: java.lang.IllegalStateException: Workbench has not been created yet.
	at org.eclipse.ui.PlatformUI.getWorkbench(PlatformUI.java:119)
	at org.eclipse.gef.internal.InternalImages.<clinit>(InternalImages.java:128)
	... 91 common frames omitted
````

It seems the problem comes from this line:

https://github.com/eclipse/gef-classic/blob/9bd2cb9842416737cda65781b4c1c702aed10ccc/org.eclipse.gef/src/org/eclipse/gef/internal/InternalImages.java#L128

I also found that the image to load is actually stored in `org.eclipse.ui` plugin at `org.eclipse.ui_3.205.100.v20240131-1023.jar\icons\full\obj16\fldr_obj.png` .

This issue looks like the following already fixed issue #201 .

Is it possible that gef-classic does not depend on the Workbench 3 being started ?

**Comment by ptziegler** [comment]
> I also found that the image to load is actually stored in org.eclipse.ui plugin at org.eclipse.ui_3.205.100.v20240131-1023.jar\icons\full\obj16\fldr_obj.png .

That is correct. The shared images only exist in the E3 world.

> This issue looks like the following already fixed issue https://github.com/eclipse/gef-classic/issues/201 .

I don't think those issues are related. The other one is caused because the bundle was loaded before the workbench was created (regardless of whether it's the E3 or E4 workbench) and therefore the system colors weren't initialized.

> Is it possible that gef-classic does not depend on the Workbench 3 being started ?

I can't say whether there are any other references to the E3 workbench. But at least for this icon, it should be simple enough to copy the png to the GEF project and use that instead.

**Comment by ptziegler** [comment]
With the upcoming milestone, this image is no longer loaded from the Eclipse 3 workbench. Can you give it a try and check if there is anything I've missed?

Out of interest: You mentioned GEF 3.11 but as far as I can tell, the issue also should've existed there. Did this old version work with the E4 application?

**Comment by cedric780** [comment]
Thanks for the fix 👍 :-)
Yes it did work without this kind of problem.
I am not sure about the version, here are the files in our target platform:

/rcp-target/org.eclipse/gef-draw2d/features/org.eclipse.draw2d_3.10.100.201705231123.jar
/rcp-target/org.eclipse/gef-draw2d/features/org.eclipse.gef_3.11.0.201705231123.jar
/rcp-target/org.eclipse/gef-draw2d/plugins/org.eclipse.draw2d_3.10.100.201705231123.jar
/rcp-target/org.eclipse/gef-draw2d/plugins/org.eclipse.gef_3.11.0.201705231123.jar

**Comment by ptziegler** [comment]
Hm... now that is weird. Based on the versions, this should correspond to the [4.0.0](https://download.eclipse.org/tools/gef/updates/legacy/milestones/4.0.0_gef-master_1952/) GEF release. Except that the release was made in 2016, not 2017 and also contains the same problem:

https://github.com/eclipse/gef-classic/blob/46841109657776d4e5317b64694592d9f5d22278/org.eclipse.gef/src/org/eclipse/gef/internal/InternalImages.java#L126-L129

Are those jars signed (i.e. do they contain an ECLIPSE_.RSA and ECLIPSE.SF file in the META-INF folder)? Because I can't find then in our update site, so I'm starting to question whether they really come from us...

**Comment by cedric780** [comment]
Ok, I digged into the jars with their sources and you are right 🥇 : the plugins have been modified and repackaged by our team ... to fix this exact issue :smile: :

```java
		DESC_SEPARATOR = createDescriptor("icons/separator.gif"); //$NON-NLS-1$
		//DESC_FOLDER_OPEN = PlatformUI.getWorkbench().getSharedImages()
		//		.getImageDescriptor(ISharedImages.IMG_OBJ_FOLDER);
		DESC_FOLDER_OPEN = createDescriptor("icons/folder_opened.gif"); //$NON-NLS-1$s
```

**Comment by ptziegler** [comment]
That's what I thought. Let's hope there aren't any other surprises. 😅

As mentioned, the first milestone was released yesterday, containing the updated icon: https://download.eclipse.org/tools/gef/classic/milestone/S202409301913
Can you check is this was already sufficient for your product?

**Comment by cedric780** [comment]
I finished checking, and it works! 🥳 
Many thanks for the quick fix 🙇
